// GENERATED — do not edit by hand.
// Source of truth: acter-core IPC types (crates/acter-core/src/entities/).
// Regenerate: cargo test -p acter-app --test protocol_bindings
// This file has been generated by Specta. Do not edit this file manually.
/**  What to say. Only `ReadAloud` carries words; the frontend owns every other sentence. */
export type Announcement = { kind: "ReadAloud"; text: string } | 
/**  Past the auto-read threshold, announced by line count. */
{ kind: "TooBig"; lines: number } | 
/**  The patience window elapsed with output still flowing. */
{ kind: "StillRunning" } | 
/**  The babble guard tripped: output keeps arriving in the buffer, unannounced. */
{ kind: "OutputContinues" } | 
/**  Nonzero exit code. */
{ kind: "Failed"; exit_code: ExitCode };

/**  Minted per attempt, so an answer to an abandoned dialog never resolves a newer attempt. */
export type AttemptId = number;

export type CommandId = number;

/**  What the person decided; never serialized, since [`Secret`](crate::Secret) cannot be. */
export type ConnectAnswer = 
/**  Trust this server and record it. */
{ answer: "Trust" } | { answer: "Password"; secret: Secret } | 
/**  The only way to reach [`ProgramAnswer::Start`](crate::ProgramAnswer). */
{ answer: "StartAnyway" } | 
/**
 *  The only way to reach [`SetupAnswer::SetUp`](crate::SetupAnswer); `remember` is kept
 *  per shell, not per host or profile.
 */
{ answer: "SetUpSession"; remember: boolean } | 
/**  Refused, cancelled, or closed. */
{ answer: "GiveUp" };

/**  What a person is asked, mid-connection. */
export type ConnectQuestion = { question: "HostKey"; host: string; port: number; 
/**  As `ssh-keygen -l` prints it. */
fingerprint: string; 
/**  The fingerprint on file, and `None` for a host with no record. */
recorded: string | null; 
/**
 *  Something true that is not the answer, such as an unreadable `known_hosts`, and
 *  `None` when there is nothing.
 */
aside: string | null } | 
/**  The file this machine is about to start did not verify. */
{ question: "Unverified"; label: string; 
/**  The full path. */
program: string; 
/**  Whole sentences ending in what to do next. */
said: string; 
/**  Who signed it, and `None` when nothing could be read. */
signer: string | null } | 
/**  What Acter would run inside this shell to integrate it. */
{ question: "SetUpSession"; shell: string; detected: string; offer: string; command: string; refusal: string } | { question: "Password"; host: string; user: string; 
/**  Whether a password was already tried and refused. */
again: boolean };

/**
 *  One thing that happens while a connection is being made; `Arrived` or `Failed` ends the
 *  sequence.
 */
export type ConnectStep = 
/**  A complete sentence, spoken as it arrives. */
{ step: "Progress"; said: string } | { step: "Asked"; attempt: AttemptId; question: ConnectQuestion } | { step: "Arrived"; connected: Connected } | 
/**  One sentence a listener can act on. */
{ step: "Failed"; why: string };

/**  One row of the connect list: one per kind, whatever this machine has of it. */
export type Connectable = {
	/**  What starts the row when no variant is chosen; for WSL, the default distribution. */
	id: ProfileId,
	/**  Ends in `(not available)` when this machine cannot start it. */
	label: string,
	available: boolean,
	/**  What to say about a row that cannot be connected to, and `None` when it can. */
	instructions: string | null,
	/**
	 *  WSL's distributions, or one entry per PowerShell install; empty when the row starts
	 *  itself.
	 */
	variants: Variant[],
};

/**  Which far end this window is on now; `use_profile` and `connected` both answer it. */
export type Connected = {
	/**  Minted per connection, so a line aimed at a replaced session is refused. */
	session: SessionId,
	label: string,
	/**  Appended once to the connection announcement, and `None` when there is nothing to add. */
	note: string | null,
	/**
	 *  Whether `note` already said this session cannot report how a command went, so
	 *  `IntegrationUnavailable` is not spoken again.
	 */
	limit_explained: boolean,
	/**  The saved connection this session was started from, or `None` for an unsaved one. */
	saved_as: string | null,
	line_owner: LineOwner,
};

export type ConnectionKind = "Cmd" | 
/**  One row; its editions are the two below. */
"PowerShell" | 
/**  5.1, shipped with Windows. */
"WindowsPowerShell" | 
/**  7 or later. */
"PowerShellSeven" | "Wsl" | 
/**  A macOS login shell, with `/etc/shells` as its variants. */
"Terminal" | "Ssh";

export type ConnectionState = 
/**  Started, and nothing has arrived from the far end yet. */
"Connecting" | "Connected" | "Reconnecting" | "Disconnected";

export type ExitCode = number;

/**
 *  Only keys [`key_bytes`](crate::key_bytes) has a measured spelling for; a new variant needs
 *  its measured bytes there.
 */
export type Key = { Char: string } | "Up" | "Down" | "Left" | "Right" | "Home" | "End" | "Tab" | "Enter" | "Backspace" | "Delete" | "Escape";

/**  What became of a keystroke. */
export type KeyAck = "Unbound" | "Applied" | 
/**  Bound, but no command was running, or nothing was left listening. */
"NothingToActOn" | 
/**  Bound, but this far end has no measured bytes for it. */
"Unsupported";

/**  One keystroke the frontend did not consume. */
export type KeyPress = {
	key: Key,
	ctrl: boolean,
	shift: boolean,
	alt: boolean,
};

/**  What the command line asked this launch to connect to. */
export type LaunchRequest = 
/**  The name as the document spells it, not as the switch did. */
{ request: "Connect"; name: string } | 
/**
 *  Nothing is saved under this name, and [`said`](Self::Unknown::said) is what the
 *  unconnected window announces instead.
 */
{ request: "Unknown"; name: string; said: string };

/**
 *  Minted once per line, never reused, unique across the session; not a grid row.
 * 
 *  Exported as `u32` because `specta-typescript` refuses `u64`.
 */
export type LineId = number;

/**  Who owns the line being edited; only the user moves it, never an inference. */
export type LineOwner = 
/**  Acter's history and completion, and nothing reaches the far end until Enter. */
"Local" | 
/**  Every key Acter does not consume goes to the far end as it is typed. */
"FarEnd";

/**
 *  Speech reads `Appended` and `Settled` and never `Rewritten`, so a spinner is not read
 *  mid-spin.
 */
export type LineRevision = 
/**  The text is only what was added to the end of the line. */
"Appended" | 
/**  The text is the whole line. */
"Rewritten" | 
/**
 *  The text is the whole line, which can no longer change and emits nothing further.
 *  Sent when it leaves the screen area, its block closes, the screen switches or the
 *  terminal resizes, never at a newline.
 */
"Settled";

export type MenuAction = 
/**  Opens the saved connections. */
"Connect" | 
/**  Opens the connection kinds. */
"NewConnection" | "SaveConnection" | "Help" | "About";

export type Mode = 
/**  Local edit field and results buffer. */
"NonInteractive" | 
/**  Full terminal pass-through. */
"Interactive";

/**  One thing that can be started: which far end, and which of it. */
export type ProfileId = 
/**  `Wsl` here means whatever distribution WSL calls the default. */
{ profile: "Shell"; kind: ConnectionKind } | 
/**
 *  One install, carrying the file discovery resolved, so the file verified is the file
 *  started.
 */
{ profile: "Install"; kind: ConnectionKind; program: string; 
/**
 *  `preview`, `Microsoft Store` or the install's directory, and `None` when nothing
 *  needs telling apart.
 */
provenance: string | null } | 
/**  Spelled as `wsl.exe -l -q` spelled it. */
{ profile: "Distribution"; name: string } | 
/**  A program named by `ACTER_SHELL`. */
{ profile: "Program"; program: string } | { profile: "Ssh"; host: string; port: number; user: string } | 
/**  A built-in scenario name or a transcript path; debug builds only. */
{ profile: "Scripted"; name: string };

/**  The saved connections resolved against this machine, as the Connect dialog lists them. */
export type SavedConnections = {
	/**  Sorted by name without case, and never reordered by use. */
	rows: SavedRow[],
	/**  What went wrong with a document that would not parse, and `None` when nothing did. */
	unreadable: string | null,
};

/**  One saved connection, as a row in that list. */
export type SavedRow = {
	name: string,
	/**  Resolved against this machine's installs, not copied from the document. */
	id: ProfileId,
	/**  Heard on arrowing onto the name: "SSH, marlon at example.org". */
	summary: string,
	set_up: SetUp,
	line_owner: LineOwner,
	available: boolean,
	/**  What to do about a row that cannot be started, and `None` when it can. */
	instructions: string | null,
};

/**
 *  Never give this `Display` or `Serialize`, and never let `Debug` print the value, or a
 *  password can reach a log or the debug event tape; it does not scrub memory.
 */
export type Secret = string;

/**  Everything the backend streams to the frontend about one session. */
export type SessionEvent = 
/**
 *  OSC 133 C. `command_line` is what the shell echoed between B and C, and `None` when
 *  there was no echo or it could not be told apart from the prompt.
 */
{ type: "CommandStarted"; command_id: CommandId; command_line: string | null } | 
/**
 *  What to put in the buffer, never what to say; speech is only ever an
 *  [`Announce`](SessionEvent::Announce).
 */
{ type: "Output"; command_id: CommandId; line: LineId; revision: LineRevision; text: string } | 
/**
 *  OSC 133 D. A nonzero exit code follows as `Announce { Failed }`; a zero one is never
 *  sent.
 */
{ type: "CommandFinished"; command_id: CommandId } | 
/**
 *  Emitted only when the shell reports exit codes; otherwise the prompt already arrives as
 *  output.
 */
{ type: "PromptDrawn"; text: string } | 
/**  The user stopped the command; no `CommandFinished` follows. */
{ type: "CommandInterrupted"; command_id: CommandId } | 
/**
 *  The startup grace period passed with no shell-integration marker; a marker arriving
 *  later upgrades the session silently.
 */
{ type: "IntegrationUnavailable" } | { type: "AltScreenEntered" } | { type: "AltScreenLeft" } | { type: "TitleChanged"; title: string } | 
/**
 *  The far end's command line in far-end-line mode; `text` is `None` when only the caret
 *  moved, and `caret` counts characters from the anchor column.
 */
{ type: "FarEndLine"; text: string | null; caret: number } | { type: "ConnectionChanged"; state: ConnectionState } | 
/**
 *  Always sent after the `Output` it speaks about, on the same in-order channel, so
 *  spoken text is already in the buffer.
 */
{ type: "Announce"; command_id: CommandId; announcement: Announcement };

/**  `u32` so it fits a JavaScript number exactly. */
export type SessionId = number;

/**
 *  Whether this connection may set its session up; not asking again about a shell is
 *  kept separately, behind [`Explained`](crate::Explained).
 */
export type SetUp = 
/**  Ask, unless told not to about this shell, then send the line. */
"Yes" | "No";

/**  The immediate answer to `submit_command`. */
export type SubmitAck = 
/**  The id every later `CommandStarted`, `Output` and `CommandFinished` of this line carries. */
{ status: "Accepted"; command_id: CommandId } | 
/**  No session is behind this window and nothing was written; the frontend owns the sentence. */
{ status: "NotConnected" };

/**  One entry in a connect-list row's panel. */
export type Variant = {
	id: ProfileId,
	/**  Named without its kind: "Ubuntu", not "WSL: Ubuntu". */
	label: string,
	/**  Always true for a WSL distribution, since only installed ones can be enumerated. */
	available: boolean,
	/**  What to say about a variant that cannot be started, and `None` when it can. */
	instructions: string | null,
};
