// GENERATED — do not edit by hand.
// Source of truth: acter-core IPC types (crates/acter-core/src/entities/).
// Regenerate: cargo test -p acter-app --test protocol_bindings
// This file has been generated by Specta. Do not edit this file manually.
/**
 *  What to say. Only reading output aloud carries text; every other announcement
 *  carries the data the frontend needs to build a pinned string it already owns.
 */
export type Announcement = 
/**  Read this span aloud: it is under the auto-read threshold. */
{ kind: "ReadAloud"; text: string } | 
/**
 *  Over the threshold — announced by size, not read. Carries no text on purpose:
 *  the span is already rendered, and past the threshold the actor stops holding it.
 */
{ kind: "TooBig"; lines: number } | 
/**  The patience window elapsed with output still flowing. */
{ kind: "StillRunning" } | 
/**  The babble guard tripped: output keeps arriving in the buffer, unannounced. */
{ kind: "OutputContinues" } | 
/**  The command ended with a nonzero exit code. */
{ kind: "Failed"; exit_code: ExitCode };

/**
 *  Correlation id tying a submitted command to every event about it. `submit_command`
 *  returns one; every later event about that command carries it. `u32` for the same
 *  reason as [`SessionId`].
 */
export type CommandId = number;

/**
 *  One thing a user can connect to, as [`ConnectApi::connectable`](crate::ConnectApi)
 *  answers and the connect list renders it.
 * 
 *  **Not the same value as [`Connection`](crate::Connection), and the difference is the
 *  point.** B5.4's catalogue is a pure function over connection *kinds*: it decides what
 *  belongs on this platform, in what order, and how a missing one reads. This is what that
 *  catalogue becomes once a real machine has answered — one row per WSL distribution
 *  rather than one row for WSL, the scripted sessions appended in a debug build, and every
 *  row carrying the id that starts it.
 */
export type Connectable = {
	/**  What to hand [`ConnectApi::use_profile`](crate::ConnectApi) to start this one. */
	id: ProfileId,
	/**
	 *  What the user hears: "Command Prompt", "PowerShell 7", "WSL: Ubuntu", with
	 *  `(not available)` on the end when this machine cannot start it.
	 * 
	 *  **The label belongs to the profile, not to the adapter** (spec B5.1, decision 3),
	 *  which is how two rows can share one adapter — the two PowerShell editions do, and
	 *  so does every WSL distribution.
	 */
	label: string,
	/**
	 *  Whether choosing this row can start a session.
	 * 
	 *  A row that cannot is still listed, still focusable and still says so in its name,
	 *  because a list that silently omits WSL teaches a listener that Acter does not
	 *  support it (spec B5.4).
	 */
	available: boolean,
	/**
	 *  What to say about a row that cannot be connected to, and `None` when it can — a
	 *  panel of instructions under a working row is noise a listener has to arrow past.
	 */
	instructions: string | null,
};

/**
 *  Which far end this window is on now, and what to call it.
 * 
 *  Returned by both `use_profile` and `connected`, because they answer the same question:
 *  the first having just changed the answer, the second having merely been asked.
 */
export type Connected = {
	/**
	 *  The new session's id, which every later invoke about it carries.
	 * 
	 *  **Minted per connection rather than fixed at 1**, so a line submitted to the
	 *  session the user just replaced is refused rather than run in the new one — the id
	 *  finally identifies something (spec B7, decision 4).
	 */
	session: SessionId,
	/**
	 *  What to call it: the same words the connect list used, so what a user chose and
	 *  what the window then calls itself are not two different names for one thing
	 *  (spec A9).
	 */
	label: string,
};

/**
 *  One thing a user can choose to connect to.
 * 
 *  Deliberately not carrying the adapter that starts it: this is what the connect list is
 *  made of, and the list exists on machines where the thing cannot be started at all.
 */
export type ConnectionKind = 
/**  `cmd.exe`, which is on every Windows machine and cannot be removed. */
"Cmd" | 
/**  Windows PowerShell 5.1, which ships with Windows. */
"WindowsPowerShell" | 
/**  PowerShell 7 or later, which is installed separately. */
"PowerShellSeven" | 
/**  Bash inside a WSL distribution. */
"Wsl";

/**
 *  Transport connection state. The local transport is always [`ConnectionState::Connected`]
 *  in Phase 1; the other states are exercised once SSH lands.
 */
export type ConnectionState = 
/**
 *  The session has been started and is not usable yet: a process was spawned, or a
 *  network connection is being made, and the far end has not said anything.
 * 
 *  **Added by A9 because it is the state a user meets first**, and the one they were
 *  never told about: a window opening onto PowerShell sat silent for seconds while the
 *  shell started, which a listener cannot tell from a session that is broken (roadmap
 *  23.7). It is deliberately not "the process exists" — a shell that has not drawn a
 *  prompt is not one anybody can use, and reporting it as connected is a lie a listener
 *  would act on.
 */
"Connecting" | "Connected" | "Reconnecting" | "Disconnected";

/**  Process exit status. Nonzero is a failure, announced distinctly from success. */
export type ExitCode = number;

/**
 *  Which key, with exactly the one variant something presses today.
 * 
 *  Named variants (Tab, Escape, the arrows, the function keys) arrive when an entry
 *  needs them — Tab with A4's completion, the rest with phase 2's pass-through key —
 *  and not before. Shipping the whole keyboard now would be a dozen variants with no
 *  consumer, which is the shape B1 refused to create and B3.5 decision 10 restated
 *  (spec B6, decision 6).
 */
export type Key = 
/**  A character key, as the frontend read it off the keyboard event. */
{ Char: string };

/**
 *  What became of a keystroke: the two questions the frontend cannot answer itself.
 * 
 *  A key nothing is bound to and a bound key that found nothing running are different
 *  things to say to a listener, so they are different answers here. Which words each
 *  one becomes is the frontend's (A3.2); this only reports what happened.
 */
export type KeyAck = 
/**  No binding for this keystroke. Nothing was attempted. */
"Unbound" | 
/**  Bound, and acted on: the intent reached the session. */
"Applied" | 
/**
 *  Bound, but there was no running command to act on.
 * 
 *  The honest answer to A3.1 decision 6's "nothing to stop", which the typed `stop`
 *  had no way to give.
 */
"NothingToActOn";

/**
 *  One keystroke the frontend did not consume, described rather than interpreted.
 * 
 *  Modifiers are flags rather than a set because a keystroke has exactly these three
 *  and a listener never asks "which modifiers", only "was Ctrl held".
 */
export type KeyPress = {
	key: Key,
	ctrl: boolean,
	shift: boolean,
	alt: boolean,
};

/**
 *  Rendering mode over the one live session. Phase 1 only ever emits
 *  [`Mode::NonInteractive`]; the interactive variant is defined so Phase 2 is additive.
 */
export type Mode = 
/**  Conversational, screen-reader-native mode: local edit field + results buffer. */
"NonInteractive" | 
/**  Full terminal pass-through for ncurses/full-screen programs. */
"Interactive";

/**
 *  One thing that can be started: which far end, and which of it.
 * 
 *  **A typed value rather than an opaque string**, so the factory that turns one into a
 *  running session matches exhaustively and a variant cannot be added without somebody
 *  deciding how to start it. It crosses the wire because the connect list is rendered by
 *  the frontend and handed back unchanged.
 */
export type ProfileId = 
/**
 *  One of the catalogue's kinds, started however that kind is started.
 * 
 *  `Wsl` here is legal and means "whatever distribution WSL calls the default", which
 *  is a real session and the one `wsl.exe` with no arguments opens. The connect list
 *  never offers it, because that list can name the distributions and a user choosing
 *  by ear is better served by a name than by "the default".
 */
{ profile: "Shell"; kind: ConnectionKind } | 
/**  Bash inside one named WSL distribution, spelled as `wsl.exe -l -q` spelled it. */
{ profile: "Distribution"; name: string } | 
/**
 *  A program named directly rather than chosen from a list: what `ACTER_SHELL` carries
 *  today, and what B8's saved profiles will carry.
 * 
 *  Started with whatever adapter recognises the name, and with none at all if nothing
 *  does — which is a session Acter supports and says nothing about.
 */
{ profile: "Program"; program: string } | 
/**
 *  One of the scripted far ends: a built-in name, or a path to a transcript.
 * 
 *  **Debug builds only.** A release build does not hide these — it never lists them
 *  and never constructs them (spec B7, decision 7).
 */
{ profile: "Scripted"; name: string };

/**  Everything the backend streams to the frontend about one session. */
export type SessionEvent = 
/**
 *  The command block opened: its output region has begun (OSC 133 C).
 * 
 *  `command_line` is what the shell echoed for this block (the B..C region), which
 *  is the shell itself saying which line it read. The frontend prefers it over the
 *  optimistic heading it put on the block when the submission was acked, so an id
 *  that drifted can no longer put the wrong words on a block (spec B6.1, decision 1).
 * 
 *  `None` is a real state and not a missing value: an unintegrated session has no
 *  B..C region at all, a shell may emit `C` with nothing echoed before it, and an
 *  echo the service could not read apart from the prompt it was written after is
 *  deliberately reported as unknown. The frontend's answer to `None` is to keep the
 *  heading it has.
 */
{ type: "CommandStarted"; command_id: CommandId; command_line: string | null } | 
/**
 *  A coalesced quiescent chunk of output. Rendering only: it says what to put in
 *  the buffer and never what to say about it. Whether any of it is spoken is a
 *  separate [`Announce`](SessionEvent::Announce) (A6).
 */
{ type: "Output"; command_id: CommandId; text: string } | 
/**
 *  The command block closed (OSC 133 D).
 * 
 *  Carries no exit code. A nonzero one arrives as `Announce { Failed }`, after the
 *  remainder of the output, which is the order a listener needs: the error text
 *  first, the verdict about it second. A successful command's code is therefore not
 *  on the wire at all — nothing read it, and the frontend must not speak it (A6
 *  decision 2). A later feature wanting the code adds a shape for it deliberately.
 */
{ type: "CommandFinished"; command_id: CommandId } | 
/**
 *  The shell drew a prompt, and this is what it says.
 * 
 *  **Restores what shell integration took away** (spec B5.6). The prompt is where a
 *  terminal user reads their working directory, their git branch, their virtualenv —
 *  and in a session marking all four boundaries it lives in the `A..B` region, which
 *  block content excludes, so a listener heard it nowhere at all. `D` replaced the
 *  prompt as an *ending signal* and replaced nothing about what it *says*.
 * 
 *  **Its own event rather than block content.** A prompt admitted as output would
 *  arrive inside a block, before that block's verdict, reading as though the shell had
 *  printed it. It is not output: it is the state the next command will run in.
 * 
 *  Only a `ShellMarkers::Full` session emits it. A shell that marks only its prompt and
 *  command line already speaks the prompt as content, because with no `D` the returning
 *  prompt is the only ending it has (spec B4.5, decision 4) — emitting this as well
 *  would say everything twice.
 */
{ type: "PromptDrawn"; text: string } | 
/**
 *  The command was stopped before it ended on its own. Terminal: no
 *  `CommandFinished` follows. Distinct from `CommandFinished` on purpose — the exit
 *  code of a process the user stopped carries no information worth announcing, and
 *  inferring "stopped" from a conventional code (130 on Unix, `0xC000013A` on
 *  Windows) would mis-announce a program that genuinely exits with it.
 */
{ type: "CommandInterrupted"; command_id: CommandId } | 
/**
 *  The startup grace period elapsed with no shell-integration markers: this session
 *  has no command boundaries and every command in it degrades to patience-only
 *  behavior (DESIGN's reliability case 2).
 * 
 *  Session-scoped and carrying no `command_id`, the shape `AltScreenEntered` and
 *  `AltScreenLeft` already have, because it fires at session start before any
 *  command exists — which is why it is not an
 *  [`Announce`](SessionEvent::Announce), whose payload is about a command. Reusing
 *  `ConnectionChanged` was rejected: that describes the transport, and "the pipe is
 *  down" and "the shell did not announce itself" must not sound alike to a listener
 *  (spec B6, decision 11).
 * 
 *  Recovery is silent: a marker arriving later upgrades the session (DESIGN
 *  decision 8) and nothing is said, because there is nothing the user must do
 *  differently.
 */
{ type: "IntegrationUnavailable" } | 
/**  A program entered the alternate screen (ncurses/full-screen); interactive mode needed. */
{ type: "AltScreenEntered" } | 
/**  The alternate screen was left; non-interactive rendering resumes. */
{ type: "AltScreenLeft" } | 
/**  The terminal title changed. */
{ type: "TitleChanged"; title: string } | 
/**  The transport connection state changed. */
{ type: "ConnectionChanged"; state: ConnectionState } | 
/**
 *  Something should be said. Speaking is its own event: as long as one event type
 *  could mean both "render this" and "say this", the two paths DESIGN separates stay
 *  coupled in the type system. The frontend appends [`SessionEvent::Output`] to the
 *  buffer and routes this to the announcer, with no branching between them.
 * 
 *  Ordering carries the invariant: the actor emits the rendering event covering a
 *  span before any `Announce` about it, and the per-session channel delivers in
 *  order, so text is always in the buffer before it is spoken. Nothing correlates
 *  the two — an announcement is self-contained, which is why a rendered span being
 *  evicted under the frontend's line cap can never silence one.
 */
{ type: "Announce"; command_id: CommandId; announcement: Announcement };

/**
 *  Identifies a session (one per tab). A distinct named type so it can never be
 *  confused with a [`CommandId`]; serializes as a bare integer. `u32` (not `u64`)
 *  because it maps to a JS `number` without precision loss and a session/tab counter
 *  never approaches four billion.
 */
export type SessionId = number;

/**
 *  The immediate answer to `submit_command`.
 * 
 *  **Two answers rather than one since B7**, because there are now two things that can
 *  become of a submitted line. A window that is not connected to anything is a state a
 *  user can be in from the moment Acter opens, and a line typed into it has to be
 *  *answered* rather than swallowed: silence is indistinguishable from a shell that is
 *  thinking, and the text the user typed has to survive so they can connect and press
 *  Enter again (spec B7, decision 3).
 */
export type SubmitAck = 
/**
 *  Accepted: this is the id correlating this submission with its `CommandStarted` /
 *  `Output` / `CommandFinished` events.
 */
{ status: "Accepted"; command_id: CommandId } | 
/**
 *  There is no session behind this window, so nothing was written anywhere.
 * 
 *  Carries no sentence: what a listener hears is the frontend's pinned string, the
 *  same one the unconnected window announced when it opened, because hearing the same
 *  words twice is how a user learns this is one state rather than two problems.
 */
{ status: "NotConnected" };
